### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by charj**

### CODE REVIEW

**Review by Irishstevie — APPROVED** [review]
Bump version would help with support

**Comment by Manason** [comment]
Why 1.2.0 from 1.0.0? This should also probably be paired with a tag on this repo. Feel like we need a project level plan for handling versioning.

**Comment by charj** [comment]
@Manason I went to `1.2.0` as its consistent with the rest of the vesion bumps.
I agree a tag would be a good plan also.

**Review by Z3rio — APPROVED** [review]
LGTM

**Pull request merged**
