### PR TITLE
Improved Pawn Shop

### PR DESCRIPTION
**Pull request by Demo4889**
Callback from server side to get your inventory and compare it to the items that can be sold in the pawn shop. Populates menu with the items you have that you can sell.

### CODE REVIEW

**Comment by colormeblind23** [comment]
Awesome improvement, not gonna lie though the removal of melting items makes me sad. Not sure why you would want to remove a neat thing as melting down items for more profitable ones like gold bars.

**Comment by Demo4889** [comment]
> Awesome improvement, not gonna lie though the removal of melting items makes me sad. Not sure why you would want to remove a neat thing as melting down items for more profitable ones like gold bars.

I actually completely forgot about that part because it's been a couple days since I worked on improving the menu. I'll work on adding that portion back in the same way and adding an input box for how much you want to sell/melt.

**Comment by Demo4889** [comment]
@colormeblind23 I re-added the melting to the pawnshop location itself. It will only show the items you currently have in your inventory (specified in the config file) that you can melt.

**Comment by evanillaa** [comment]
nice work thank you bro

**Comment by darknight2590** [comment]
add this
https://github.com/qbcore-framework/qb-pawnshop/pull/4
https://github.com/qbcore-framework/qb-pawnshop/pull/3

**Comment by Demo4889** [comment]
@darknight2590 why would I need to add those? There's nothing in my improvements that needs that

**Pull request merged**
